services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_tags.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tags.settings
