services:
  - type: web
    name: django-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_tags.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tags.settings
      - key: PYTHON_VERSION
        value: 3.11
